download.file("https://raw.githubusercontent.com/markziemann/SLE712_files/master/bioinfo_asst3_part1_files/gene_expression.tsv", destfile = "gene_expression.tsv")

# Ques 1: Read in the file, making the gene accession numbers the row names. Show a table of values for the first six genes
gene <- read.table("gene_expression.tsv")
head(gene) # Show a table of values for the first six genes
str(gene)

# Ques 2: Make a new column which is the mean of the other columns. Show a table of values for the first six genes.

gene <- read.table("gene_expression.tsv" , header = TRUE, stringsAsFactors = FALSE, row.names = 1)
gene$Means <- rowMeans(gene)
head(gene)
str(gene)


# Ques 3: List the 10 genes with the highest mean expression
order(gene$Mean)
gene[order(gene$Mean), ]
gene[order(-gene$Mean), ]
head(gene[order(-gene$Mean), ])
head(gene[order(-gene$Mean), ], 10)

# Ques 4: Determine the number of genes with a mean <10
subset(gene,Mean<10)
filtered <- subset(gene,Mean<10)
nrow(filtered)

# Ques 5: Make a histogram plot of the mean values in png format and paste it into your report.
hist(gene$Mean)
hist(gene$Mean, breaks = 20)

---------------------------------------------------------------------------------------------------------------------------------
download.file("https://raw.githubusercontent.com/markziemann/SLE712_files/master/bioinfo_asst3_part1_files/growth_data.csv", destfile = "growth_data.csv")
y <- read.csv("growth_data.csv")
#subset(y,Site=="northeast")
head(y)
str(y)

# Ques 6: Import this csv file into an R object. What are the column names?
download.file("https://raw.githubusercontent.com/markziemann/SLE712_files/master/bioinfo_asst3_part1_files/growth_data.csv", destfile = "growth_data.csv")
y <- read.table("growth_data.csv", header = TRUE, stringsAsFactors = FALSE)
head(y)
str(y)
ncol(y)
colnames(y)

# ques 7: Calculate the mean and standard deviation of tree circumferance at the start and end of the study at both sides.
y<-read.csv("growth_data.csv")
subset(y,Site=="northeast")
ne <- subset(y,Site=="northeast")
head(ne)
tail(ne)
str(ne)
mean(ne$Circumf_2004_cm)
mean(ne$Circumf_2019_cm)
sd(ne$Circumf_2004_cm)
sd(ne$Circumf_2019_cm)

y<-read.csv("growth_data.csv")
subset(y,Site=="southwest")
sw <- subset(y,Site=="southwest")
head(sw)
tail(sw)
str(sw)
mean(sw$Circumf_2004_cm)
mean(sw$Circumf_2019_cm)
sd(sw$Circumf_2004_cm)
sd(sw$Circumf_2019_cm)

# ques 8: make a box plot of tree circumferance at the start and end of the study of both sides.
boxplot(ne$Circumf_2004_cm, ne$Circumf_2019_cm)
boxplot(ne$Circumf_2004_cm, ne$Circumf_2019_cm, sw$Circumf_2004_cm, sw$Circumf_2019_cm)
boxplot(ne$Circumf_2004_cm, ne$Circumf_2019_cm, sw$Circumf_2004_cm, sw$Circumf_2019_cm, names = c("ne2004", "ne2019", "sw2004", "sw2019"), ylab="Circumfrence (cm)")
boxplot(ne$Circumf_2004_cm, ne$Circumf_2019_cm, sw$Circumf_2004_cm, sw$Circumf_2019_cm, names = c("ne2004", "ne2019", "sw2004", "sw2019"), ylab="Circumfrence (cm)", main="Growth at two plantation sites")

# Ques 9: Calculate the mean growth over the past 10 years at each site.

ne$growth <-ne$Circumf_2019_cm-ne$Circumf_2009_cm
head(ne)

sw$growth <-sw$Circumf_2019_cm-sw$Circumf_2009_cm
head(sw)

# Ques 10: Use the t.test and wilcox.test functions to estimate the p-value that the 10 year growth is different at the two sites

t.test(sw$growth,ne$growth)
wilcox.test(sw$growth,ne$growth)

=======
--------------------------------------------------------------------------------------------------------------------------------
Part 2: Determine the limits of BLAST

# Ques 1: Download the whole set of E. coli g ene DNA sequences and use gunzip to decompress. Use the makeblast() function to create a blast database. How many sequences are present in the E.coli set?


download.file("ftp://ftp.ensemblgenomes.org/pub/bacteria/release-42/fasta/bacteria_0_collection/escherichia_coli_str_k_12_substr_mg1655/cds/Escherichia_coli_str_k_12_substr_mg1655.ASM584v2.cds.all.fa.gz",destfile = "Escherichia_coli_str_k_12_substr_mg1655.ASM584v2.cds.all.fa.gz")

# Using gunzip to decompress 
R.utils::gunzip("Escherichia_coli_str_k_12_substr_mg1655.ASM584v2.cds.all.fa.gz", overwrite= TRUE)

# Makeblst() to create a blast distance
makeblastdb("Escherichia_coli_str_k_12_substr_mg1655.ASM584v2.cds.all.fa",dbtype = "nucl","-parse_seqids")

# sequences are present in the E.coli set?
4140


# Ques 2: Download the sample fasta sequences and read them in as above. For your allocated sequence, determine the length (in bp) and the proportion of GC bases.


download.file("ftp://ftp.ensemblgenomes.org/pub/bacteria/release-42/fasta/bacteria_0_collection/escherichia_coli_str_k_12_substr_mg1655/cds/Escherichia_coli_str_k_12_substr_mg1655.ASM584v2.cds.all.fa.gz", destfile = "Escherichia_coli_str_k_12_substr_mg1655.ASM584v2.cds.all.fa.gz")

# Using gunzip to decompress 
R.utils::gunzip("Escherichia_coli_str_k_12_substr_mg1655.ASM584v2.cds.all.fa.gz", overwrite= TRUE)


# Makeblst() to create a blast distance
makeblastdb("Escherichia_coli_str_k_12_substr_mg1655.ASM584v2.cds.all.fa",dbtype = "nucl","-parse_seqids")


download.file("https://raw.githubusercontent.com/markziemann/SLE712_files/master/bioinfo_asst3_part2_files/sample.fa",destfile = "sample.fa")

# Downloading file
MYDATA <- read.fasta("sample.fa")
# Saving it to mydata
mydata <- MYDATA[[28]]
# Checking the str
str(mydata)
mydata[1:50]
# Checking the length of the allocated sequence
seqinr::GC(mydata)
seqinr::getLength(mydata)
length(mydata)

##Question 3: You will be provided with R functions to create BLAST databases and perform blast searches, Use blast to identify what E. coli gene your sequence matches best. Show a table of the top 3 hits including percent identity, E-value and bit scores.

download.file("https://raw.githubusercontent.com/markziemann/SLE712_files/master/bioinfo_asst3_part2_files/mutblast_functions.R",destfile = "mutblast.R")
# 
source("mutblast.R")

#
myblastn_tab
res <- myblastn_tab(myseq = myseq, db = "Escherichia_coli_str_k_12_substr_mg1655.ASM584v2.cds.all.fa")

#
str(res)
#
res

The top 3 hits including percent identity = 100, E-value = 0 and bit scores = 2769.
The discovered gene is AAC75752


##Question 4: You will be provided with a function that enables you to make a set number of point mutations to your sequence of interest. Run the function and write an R code to check the number of mismatches between the original and mutated sequence.

##Question 5:Using the provided functions for mutating and BLASTing a sequence, determine the number and proportion of sites that need to be altered to prevent the BLAST search from matching the gene of origin. Because the mutation is random, you may need to run this test multiple times to get a reliable answer.

# Ques 6:  Provide a chart or table that shows how the increasing proportion of mutated bases reduces the ability for BLAST to match the gene of origin. Summarise the results in 1 to 2 sentences.


